# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/Zybo-Z7-Master.xdc

# Block Designs: bd/HDMI_bd/HDMI_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_bd || ORIG_REF_NAME==HDMI_bd} -quiet] -quiet

# IP: bd/HDMI_bd/ip/HDMI_bd_clk_wiz_0_0/HDMI_bd_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_bd_clk_wiz_0_0 || ORIG_REF_NAME==HDMI_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/HDMI_bd/ip/HDMI_bd_dvi2rgb_0_0/HDMI_bd_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_bd_dvi2rgb_0_0 || ORIG_REF_NAME==HDMI_bd_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/HDMI_bd/ip/HDMI_bd_rgb2dvi_0_0/HDMI_bd_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_bd_rgb2dvi_0_0 || ORIG_REF_NAME==HDMI_bd_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/HDMI_bd/ip/HDMI_bd_xlconstant_0_0/HDMI_bd_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_bd_xlconstant_0_0 || ORIG_REF_NAME==HDMI_bd_xlconstant_0_0} -quiet] -quiet

# IP: bd/HDMI_bd/ip/HDMI_bd_moyennage_0_0/HDMI_bd_moyennage_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_bd_moyennage_0_0 || ORIG_REF_NAME==HDMI_bd_moyennage_0_0} -quiet] -quiet

# IP: bd/HDMI_bd/ip/HDMI_bd_zonePeau_0_0/HDMI_bd_zonePeau_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_bd_zonePeau_0_0 || ORIG_REF_NAME==HDMI_bd_zonePeau_0_0} -quiet] -quiet

# IP: bd/HDMI_bd/ip/HDMI_bd_boite_0_0/HDMI_bd_boite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_bd_boite_0_0 || ORIG_REF_NAME==HDMI_bd_boite_0_0} -quiet] -quiet

# IP: bd/HDMI_bd/ip/HDMI_bd_MessageSend_0_0/HDMI_bd_MessageSend_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_bd_MessageSend_0_0 || ORIG_REF_NAME==HDMI_bd_MessageSend_0_0} -quiet] -quiet

# IP: bd/HDMI_bd/ip/HDMI_bd_comparaison_couleurs_0_5/HDMI_bd_comparaison_couleurs_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==HDMI_bd_comparaison_couleurs_0_5 || ORIG_REF_NAME==HDMI_bd_comparaison_couleurs_0_5} -quiet] -quiet

# XDC: bd/HDMI_bd/HDMI_bd_ooc.xdc
